version: '3'
services:
  app:
    build: .
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "8081:8081"
    command: npm start
#  web:
#    build: .
#    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
#    depends_on:
#      - postgres
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
