version: '3'
services:
  app:
    build: .
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail http://localhost/v1 || exit 1
      interval: 10sec
      timeout: 3s
      retries: 3
    command: npm start
#  web:
#    build: .
#    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
#    depends_on:
#      - postgres
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
